version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "40080:80"
      - "40443:443"
    environment:
      TZ: 'Europe/Budapest'
    volumes:
      - '/opt/pihole-storage/etc-pihole:/etc/pihole'
      - '/opt/pihole-storage/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
